name: Bot de Reservas de Madrid

on:
  # Permite ejecutarlo manualmente desde la pestaña Actions de GitHub
  workflow_dispatch:
  
  # Programador (Cron Job)
  schedule:
    # IMPORTANTE: GitHub Actions usa la hora UTC.
    # Ajusta la hora según necesites (invierno/verano).
    # "minuto hora * * dia_de_semana"
    # Ejecuta a las 09:02 UTC los Martes(2), Miércoles(3), Sábados(6) y Domingos(0).
    - cron: '01 09 * * 0,2,3,6'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Listar archivos del repositorio  
        run: |
          pwd
          ls -la
          echo "---"
          echo "Contenido completo:"
          find . -type f

      - name: Configurar Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar dependencias
        run: |
          pip install -r requirements.txt
          
      - name: Ejecutar el script del bot
        env:
          DEPORTES_USER: ${{ secrets.DEPORTES_USER }}
          DEPORTES_PASS: ${{ secrets.DEPORTES_PASS }}
        run: |
          python main.py
