name: Bot de Reservas de Madrid

on:
  workflow_dispatch:
  schedule:
    - cron: '01 09 * * 0,2,3,6'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Configurar Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Debug - Ver archivos después de checkout
        run: |
          pwd
          echo "=== Listado completo ==="
          ls -la
          echo "=== Buscando requirements.txt ==="
          find . -name "requirements.txt" -type f
          echo "=== Contenido de requirements.txt ==="
          cat requirements.txt || echo "No se pudo leer requirements.txt"

      - name: Instalar dependencias
        run: |
          pwd
          ls -la
          echo "=== Contenido de requirements.txt antes de instalar ==="
          cat requirements.txt
          echo "=== Instalando ==="
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          
      - name: Ejecutar el script del bot
        env:
          DEPORTES_USER: ${{ secrets.DEPORTES_USER }}
          DEPORTES_PASS: ${{ secrets.DEPORTES_PASS }}
        run: |
          python main.py